# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180121_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='使用markdown格式'),
        ),
    ]
