# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default='', help_text='注解:目前仅支持markdown格式', verbose_name='渲染后的内容'),
        ),
    ]
